# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Quakkels Theme"
license = "MIT"
licenselink = ""
description = ""
homepage = "http://yoururl.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Brandon Quakkelaar"
  homepage = "http://quakkels.com"
